// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEF23YD6y5VTag_fSHE0UYyFkMBKZgP8k',
    appId: '1:805671753475:web:27fb498823fee4d6007b36',
    messagingSenderId: '805671753475',
    projectId: 'myhack-ieee',
    authDomain: 'myhack-ieee.firebaseapp.com',
    storageBucket: 'myhack-ieee.appspot.com',
    measurementId: 'G-QNGNJQWTVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7bAjQbjFN40CFXrl-lErfbCSsdv3nF20',
    appId: '1:805671753475:android:160a5ca138468d77007b36',
    messagingSenderId: '805671753475',
    projectId: 'myhack-ieee',
    storageBucket: 'myhack-ieee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZv0qZUEg2e0qDhw-TdTrqPwccOxX4gM',
    appId: '1:805671753475:ios:487b90c583b2f156007b36',
    messagingSenderId: '805671753475',
    projectId: 'myhack-ieee',
    storageBucket: 'myhack-ieee.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZv0qZUEg2e0qDhw-TdTrqPwccOxX4gM',
    appId: '1:805671753475:ios:487b90c583b2f156007b36',
    messagingSenderId: '805671753475',
    projectId: 'myhack-ieee',
    storageBucket: 'myhack-ieee.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
