on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: "MyHack Build & Release"

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Run Flutter Commands
        run: | 
          cd app
          flutter config --no-analytics
          flutter pub get
          flutter build apk --debug --split-per-abi
  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Run Flutter and iOS Build Commands
        run: | 
          cd app
          flutter pub get
          flutter clean
          flutter build ios --no-codesign
  build_android:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Run Flutter and Android Build Commands
        run: | 
          cd app
          flutter pub get
          flutter clean
          flutter build appbundle
  # release:
  #   name: Push to Releases
  #   needs: [build_ios, build_android, flutter_test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Upload iOS IPA
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: ios-artifact
  #         path: app/build/ios/iphoneos/Runner.app

  #     - name: Upload Android APK
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: android-artifact
  #         path: app/build/app/outputs/flutter-apk/app-release.apk

  #     - name: Release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: |
  #           ios-artifact/**/*.ipa
  #           android-artifact/**/*.apk
  #         tag: v1.0.${{ github.run_number }}
  #         token: ${{ secrets.TOKEN }}
